### ISSUE TITLE
Exception when inspecting FailingTypes

### ISSUE THREAD

**Issue by vgaltes** [BenMorris/NetArchTest#26]
I have a test like this:

```
[Fact]
public void ControllersShouldNotReferenceRepositories()
{
    var path = Assembly.GetExecutingAssembly().Location;
    var folder = Path.GetDirectoryName(path);

    var types = Types.FromPath(folder);

    var repositoryNames = types
        .That()
        .ResideInNamespaceMatching("MyCompany.Infrastructure.Data.*")
        .GetTypes()
        .Select(t => t.FullName)
        .ToList();

    var result = types
        .That()
        .ResideInNamespaceMatching("MyCompany.API.Controllers.*")
        .ShouldNot()
        .HaveDependencyOnAny(repositoryNames.ToArray())
        .GetResult();

    result.IsSuccessful.Should().BeTrue($"The following types have a dependency on a repository: {string.Join(",", result.FailingTypes.Select(t => t.FullName))}");
}
```

What happens is that when xUnit (or myself if I'm doing it manually) tries to show the name of the FailingTypes it throws an error.

```
System.IO.FileLoadException
Could not load file or assembly 'System.Web.Http, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at NetArchTest.Rules.Extensions.TypeDefinitionExtensions.ToType(TypeDefinition typeDefinition)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at MyCompany.WebApi.ArchitectureTest.ArchitectureTests.ControllersShouldNotReferenceRepositories()
```

Is there any way to get the names of the failing types? Am I doing something wrong?

Thanks,

**Comment by kl1mm** [comment]
We encountered exact the same problem!

**Comment by BenMorris** [comment]
Ah - I think this looks like something to do with the way that dependent libraries are being loaded (or not), i.e. they are visible to NetArchTest but not to your unit test. 

I will rig up a test to replicate and fix in the next day or two. I suspect that switching TestResult.FailingTypes() from an IEnumerable to a List() will do the trick.

**Comment by kl1mm** [comment]
Hey Ben,
do u plan to release this? (Nuget)

thanks kl1mm

**Comment by BenMorris** [comment]
v1.2.3 has been pushed - it should be visible in an hour or so.
